# Generated by Django 4.2 on 2024-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesearchbykeyworditem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='articlesearchbykeyworditem',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
